version: '3.9'

services:
  media:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    ports:
      - 3000:3000
    command: npx nest start --watch
    volumes:
      - .:/app
      - nodeModulesz:/app/node_modules

volumes:
  nodeModulesz:
